# Get RHCOS base image of target cluster `oc adm release info --image-for rhel-coreos-8`
# This example uses rhel-coreos image from 4.12.11-x86_64
FROM quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:8187de75b281f1ee2da1d62ad94cf9012c73c9d4d739a9d8ca06e44dd17a29d0

# Enable cliwrap; this is currently required to intercept some command invocations made from
# kernel scripts.
RUN rpm-ostree cliwrap install-to-root /
# Replace the kernel, kernel-core and kernel-modules packages.
RUN rpm-ostree override replace http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/Packages/kernel-{,core-,modules-,modules-extra-}4.18.0-483.el8.x86_64.rpm && \
    ostree container commit
